// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtg9qRbsljld7UsfI0gbIZuN9nbvSENpA',
    appId: '1:1071373791495:web:06e1cfd5a7b50cef3395a2',
    messagingSenderId: '1071373791495',
    projectId: 'flutter-chat-app-09',
    authDomain: 'flutter-chat-app-09.firebaseapp.com',
    storageBucket: 'flutter-chat-app-09.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN3G1EFEtehj6wCRO_DTYPKuTSOfvnquM',
    appId: '1:1071373791495:android:1da04f739690bb1b3395a2',
    messagingSenderId: '1071373791495',
    projectId: 'flutter-chat-app-09',
    storageBucket: 'flutter-chat-app-09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbR6JTIR2eq_JN0deWRle6qQDU1wmgenA',
    appId: '1:1071373791495:ios:f54c513cae481b5d3395a2',
    messagingSenderId: '1071373791495',
    projectId: 'flutter-chat-app-09',
    storageBucket: 'flutter-chat-app-09.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbR6JTIR2eq_JN0deWRle6qQDU1wmgenA',
    appId: '1:1071373791495:ios:1b7f8fec4d4026eb3395a2',
    messagingSenderId: '1071373791495',
    projectId: 'flutter-chat-app-09',
    storageBucket: 'flutter-chat-app-09.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
